/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PuzzleGame;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Suneth Chathuranga
 */
public class GameBoard extends javax.swing.JFrame {

    public static final int GRIDSIZE = 4;
    public static final int NUMBER_OF_BUTTONS = GRIDSIZE*GRIDSIZE;
    private int currentMoves = 0;
    private 

    
    String [] solutionArray;

    List <BoardButton> boardButtons = new ArrayList<>();

    /**
     * Creates new form Game
     */
    public GameBoard() {

        initComponents();

        // initBoardButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Game_Name = new javax.swing.JLabel();
        gamePanel = new javax.swing.JPanel();
        detailPanel = new javax.swing.JPanel();
        movesLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        boardPanel = new javax.swing.JPanel();

        this.setBackground(Color.black);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(3, 5, 18));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Game_Name.setBackground(new java.awt.Color(0, 0, 51));
        Game_Name.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Game_Name.setForeground(new java.awt.Color(0, 153, 0));
        Game_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Game_Name.setText("PUZZLE GAME");
        getContentPane().add(Game_Name, java.awt.BorderLayout.NORTH);

        gamePanel.setLayout(new java.awt.BorderLayout());

        detailPanel.setLayout(new java.awt.BorderLayout());

        movesLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        movesLabel.setText("jLabel1");
        movesLabel.setDoubleBuffered(true);
        movesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        detailPanel.add(movesLabel, java.awt.BorderLayout.WEST);

        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeLabel.setText("jLabel1");
        timeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        detailPanel.add(timeLabel, java.awt.BorderLayout.EAST);

        gamePanel.add(detailPanel, java.awt.BorderLayout.NORTH);

        boardPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boardPanel.setLayout(new java.awt.GridLayout(4, 4, 2, 2));
        gamePanel.add(boardPanel, java.awt.BorderLayout.SOUTH);
        initBoardButtons();
        getContentPane().add(gamePanel, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        initializeTheSolutionArray();
        startTimer();

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */





    //initiate Buttons of the game board when starting the game
    public void initBoardButtons(){

        
        ActionListener buttonListener = new ActionListener() {

            //Adding clicking event to all the buttons
            @Override
            public void actionPerformed(ActionEvent e) {
                BoardButton clickedButton = (BoardButton) e.getSource();
                buttonFunction(clickedButton);
            }
        };

        for(int j=1; j<=NUMBER_OF_BUTTONS; j++){
            BoardButton newButton = new BoardButton();
            newButton.setText(Integer.toString(j));
            newButton.setPreferredSize(new Dimension(100,100));
            newButton.setBackground(Color.BLUE);
            newButton.setFont(new Font("Arial", Font.BOLD, 20));
            newButton.setForeground(Color.WHITE);
            //newButton.setBorder(new RoundedBorder(10));
            newButton.addActionListener(buttonListener);
            boardButtons.add(newButton);
            
        }
        Collections.shuffle(boardButtons);
        boardButtons.get(boardButtons.size()-1).setText("");
        for(BoardButton button : boardButtons){
            boardPanel.add(button);
        }
    }


    
    
    public void buttonFunction(BoardButton button) {
        int buttonIndex = boardButtons.indexOf(button);
    
        // Check if the button can be moved to the right
        if (buttonIndex + 1 < boardButtons.size() && boardButtons.get(buttonIndex + 1).getText().equals("")) {
            swapButtons(buttonIndex, buttonIndex + 1);
        }
        // Check if the button can be moved to the left
        else if (buttonIndex - 1 >= 0 && boardButtons.get(buttonIndex - 1).getText().equals("")) {
            swapButtons(buttonIndex, buttonIndex - 1);
        }
        // Check if the button can be moved down
        else if (buttonIndex + GRIDSIZE < boardButtons.size() && boardButtons.get(buttonIndex + GRIDSIZE).getText().equals("")) {
            swapButtons(buttonIndex, buttonIndex + GRIDSIZE);
        }
        // Check if the button can be moved up
        else if (buttonIndex - GRIDSIZE >= 0 && boardButtons.get(buttonIndex - GRIDSIZE).getText().equals("")) {
            swapButtons(buttonIndex, buttonIndex - GRIDSIZE);
        }
    }
    
    private void swapButtons(int index1, int index2) {
        BoardButton button1 = boardButtons.get(index1);
        BoardButton button2 = boardButtons.get(index2);
        button2.setText(button1.getText());
        button1.setText("");

        isPuzzleSolved();
    }

    
    
    public void initializeTheSolutionArray(){
        solutionArray = new String [NUMBER_OF_BUTTONS];

        int index=0;
        for(int i=0; i<GRIDSIZE; i++){ 
        if(i%2==0){
            for(int j=(i*GRIDSIZE)+1; j<((i+1)*GRIDSIZE)+1; j++){ 
                solutionArray[index] = Integer.toString(j);
                index++;
                System.out.println(j);
            }
            
        }
        else{
            for(int j=(i+1)*GRIDSIZE; j>(i*GRIDSIZE); j--){ 
                solutionArray[index] = Integer.toString(j);
                index++;
                System.out.println(j);
        }

        solutionArray[(GRIDSIZE%2==0)? NUMBER_OF_BUTTONS-(GRIDSIZE) : NUMBER_OF_BUTTONS-1] = "";
            
        }

        
    }
    System.out.println("Solusion Array Generated Succesfull!");
    }

    public boolean isPuzzleSolved() {
        // Iterate through the buttons and compare their text with the correct order
        for (int i = 0; i < boardButtons.size(); i++) {
            if (!boardButtons.get(i).getText().equals(solutionArray[i])) {
                return false; // Puzzle is not in correct order
            }
        }
        JOptionPane.showMessageDialog(null,"You Won!", "Congratulations!",JOptionPane.OK_CANCEL_OPTION );
        System.out.println("You Won");
        return true; // Puzzle is in correct order
    }
    

    //MARK: The_Timer_Function
    public void startTimer() {
        Timer timer = new Timer(1000, new ActionListener() {
            int seconds = 0;
            int minutes = 0;
            int hours = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                seconds++;
                if (seconds == 60) {
                    seconds = 0;
                    minutes++;
                }
                if (minutes == 60) {
                    minutes = 0;
                    hours++;
                }
                timeLabel.setText(String.format("%02d:%02d:%02d", hours, minutes, seconds));
            }
        });

        timer.start();
    }









    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Game_Name;
    private javax.swing.JPanel boardPanel;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JLabel movesLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
